load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")

scala_library(
    name = "scalac-composite-reporter",
    srcs = ["CompositeReporter.scala"],
    deps = ["@maven//:org_scala_lang_scala_compiler"],
)
